name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      working-directory: frontend
      run: npm install
    - name: Run tests
      working-directory: frontend
      run: npm run test:ci

  build-app:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: ./frontend
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/tested-app:latest

  # access-droplet:
  #   runs-on: ubuntu-latest
  #   needs: build-app
  #   steps:
  #   - name: Checkout repository
  #     uses: actions/checkout@v3

  #   - name: Copy file via scp
  #     uses: appleboy/scp-action@master
  #     env:
  #       HOST: ${{ secrets.SSH_HOST }}
  #       USERNAME: ${{ secrets.SSH_USERNAME }}
  #       KEY: ${{ secrets.SSH_KEY }}
  #     with:
  #       source: "."
  #       target: "/opt/app"

  #   - name: Executing remote  command
  #     uses: appleboy/ssh-action@master
  #     with:
  #       host: ${{ secrets.SSH_HOST }}
  #       USERNAME: ${{ secrets.SSH_USERNAME }}
  #       KEY: ${{ secrets.SSH_KEY }}
  #       script: |
  #         cd /opt/app
  #         docker-compose up --build &
